const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InRlc3QiLCJkYm5hbWUiOiIxNDEwNTgiLCJpYXQiOjE2OTkzMjM4ODMsImV4cCI6MTY5OTMyNzQ4M30.SJmeGxw1nUBaB1pjYzd57jvAxTHizzFvDjeul3hoOsk";

export default token;
